In [2]:
#AI建立一個function
#資料來源:scores = np.random.randint(50,101,size=(50, 5))
#欄位: ['國文', '英文', '數學', '自然', '社會','總分','平均','排名']
#索引: ['學生' + str(i) for i in range(1, 51)]
#建立DataFrame
import numpy as np
import pandas as pd 

def build_scores_dataframe(scores):
    df = pd.DataFrame(scores,
                      columns=['國文', '英文', '數學', '自然', '社會'],
                      index=['學生' + str(i) for i in range(1, 51)])
    df.index.name = '學生'
    df.columns.name = '科目'
    sum_values = df.sum(axis=1)
    mean_values = df.mean(axis=1)
    df['總分'] = sum_values
    df['平均'] = mean_values
    rank_values = sum_values.rank(method='min', ascending=False)
    df['排名'] = rank_values
    return df

scores = np.random.randint(50,101,size=(50, 5))
df = build_scores_dataframe(scores)
df

科目    國文   英文   數學   自然  社會   總分    平均    排名
學生
學生1   50   59   55   63  68  295  59.0  50.0
學生2   98   73   50   66  89  376  75.2  26.0
學生3   80   98   75   74  91  418  83.6   2.0
學生4   58   95   97   92  61  403  80.6  12.0
學生5   90   63   76   58  75  362  72.4  28.0
學生6   84   89   58   94  75  400  80.0  13.0
學生7   86   77   75   60  84  382  76.4  23.0
學生8   66   94   58   64  51  333  66.6  44.0
學生9   59   55   59   68  86  327  65.4  45.0
學生10  89   66   88   96  72  411  82.2   6.0
學生11  93   99   88   61  64  405  81.0   9.0
學生12  58   79   89   63  94  383  76.6  22.0
學生13  50   76   64   96  65  351  70.2  35.0
學生14  87   63   71   82  51  354  70.8  33.0
學生15  57   54   57   99  59  326  65.2  48.0
學生16  52   94   70   65  61  342  68.4  42.0
學生17  87   99   67   79  78  410  82.0   7.0
學生18  88   55   75   72  97  387  77.4  20.0
學生19  98   52   84   88  59  381  76.2  24.0
學生20  81   52   76   73  52  334  66.8  43.0
學生21  88   90   81   69  66  394  78.8  15.0
學生22  81   55  100   56  89  381  76.2  24.0
學生23  91   50   69   88  89  387  77.4  20.0
學生24  71   98   64   61  50  344  68.8  41.0
學生25  91   77   75   86  85  414  82.8   4.0
學生26  64   59   57   88  85  353  70.6  34.0
學生27  93   80   83   90  54  400  80.0  13.0
學生28  56   83   58   55  70  322  64.4  49.0
學生29  84   91   94  100  97  466  93.2   1.0
學生30  76   55   73   93  97  394  78.8  15.0
學生31  69   95   53   71  73  361  72.2  30.0
學生32  52   69   76   92  76  365  73.0  27.0
學生33  94   94   53   93  73  407  81.4   8.0
學生34  88   73   93   59  91  404  80.8  11.0
學生35  68   62   83   80  54  347  69.4  37.0
學生36  94   50   68   70  75  357  71.4  31.0
學生37  60   99   70   79  97  405  81.0   9.0
學生38  55   54   84   62  72  327  65.4  45.0
學生39  62   86   62   73  64  347  69.4  37.0
學生40  53  100   50   82  72  357  71.4  31.0
學生41  85   90   91   56  70  392  78.4  17.0
學生42  68  100   66   82  96  412  82.4   5.0
學生43  61   86   65   59  76  347  69.4  37.0
學生44  77   81   73   90  94  415  83.0   3.0
學生45  77   67   52   79  52  327  65.4  45.0
學生46  60   82   84   56  69  351  70.2  35.0
學生47  85   59   71   97  50  362  72.4  28.0
學生48  82   83   99   50  77  391  78.2  18.0
學生49  73   82   91   51  50  347  69.4  37.0
學生50  77   95   78   84  54  388  77.6  19.0

In [4]:
#還擇欄位
df1 = df[['國文', '英文', '數學', '自然', '社會']]
df1

科目    國文   英文   數學   自然  社會
學生
學生1   50   59   55   63  68
學生2   98   73   50   66  89
學生3   80   98   75   74  91
學生4   58   95   97   92  61
學生5   90   63   76   58  75
學生6   84   89   58   94  75
學生7   86   77   75   60  84
學生8   66   94   58   64  51
學生9   59   55   59   68  86
學生10  89   66   88   96  72
學生11  93   99   88   61  64
學生12  58   79   89   63  94
學生13  50   76   64   96  65
學生14  87   63   71   82  51
學生15  57   54   57   99  59
學生16  52   94   70   65  61
學生17  87   99   67   79  78
學生18  88   55   75   72  97
學生19  98   52   84   88  59
學生20  81   52   76   73  52
學生21  88   90   81   69  66
學生22  81   55  100   56  89
學生23  91   50   69   88  89
學生24  71   98   64   61  50
學生25  91   77   75   86  85
學生26  64   59   57   88  85
學生27  93   80   83   90  54
學生28  56   83   58   55  70
學生29  84   91   94  100  97
學生30  76   55   73   93  97
學生31  69   95   53   71  73
學生32  52   69   76   92  76
學生33  94   94   53   93  73
學生34  88   73   93   59  91
學生35  68   62   83   80  54
學生36  94   50   68   70  75
學生37  60   99   70   79  97
學生38  55   54   84   62  72
學生39  62   86   62   73  64
學生40  53  100   50   82  72
學生41  85   90   91   56  70
學生42  68  100   66   82  96
學生43  61   86   65   59  76
學生44  77   81   73   90  94
學生45  77   67   52   79  52
學生46  60   82   84   56  69
學生47  85   59   71   97  50
學生48  82   83   99   50  77
學生49  73   82   91   51  50
學生50  77   95   78   84  54

In [18]:
s = df1.loc['學生1']
less_than_60_series = s[s<60]
#取出不及格的科目
failing_subjects = less_than_60_series.index.tolist()
failing_subjects
#取出不及格科目的分數
failing_scores = less_than_60_series.tolist()
failing_scores
#建立一個Series,值要轉換為字串,如果有多個值則用逗號分隔
failing_scores_str = ','.join(map(str, failing_scores))
failing_subjects_str = ','.join(failing_subjects)
pd.Series([failing_scores_str, failing_subjects_str], index=['分數', '不及格科目'])

分數       50,59,55
不及格科目    國文,英文,數學
dtype: object

In [19]:
def apply_statistics(s):
    less_than_60_series = s[s<60]
    #不及格科目數量
    failing_subjects_count = less_than_60_series.count()
    #取出不及格的科目
    failing_subjects = less_than_60_series.index.tolist()
    
    #取出不及格科目的分數
    failing_scores = less_than_60_series.tolist()
    
    #建立一個Series,值要轉換為字串,如果有多個值則用逗號分隔
    failing_scores_str = ','.join(map(str, failing_scores))
    failing_subjects_str = ','.join(failing_subjects)
    return pd.Series([failing_subjects_count,failing_subjects_str,failing_scores_str], index=['不及格科目數量', '不及格科目', '分數'])


df2 = df1.apply(apply_statistics, axis=1)
df2

      不及格科目數量        不及格科目           分數
學生
學生1         3     國文,英文,數學     50,59,55
學生2         1           數學           50
學生3         0
學生4         1           國文           58
學生5         1           自然           58
學生6         1           數學           58
學生7         0
學生8         2        數學,社會        58,51
學生9         3     國文,英文,數學     59,55,59
學生10        0
學生11        0
學生12        1           國文           58
學生13        1           國文           50
學生14        1           社會           51
學生15        4  國文,英文,數學,社會  57,54,57,59
學生16        1           國文           52
學生17        0
學生18        1           英文           55
學生19        2        英文,社會        52,59
學生20        2        英文,社會        52,52
學生21        0
學生22        2        英文,自然        55,56
學生23        1           英文           50
學生24        1           社會           50
學生25        0
學生26        2        英文,數學        59,57
學生27        1           社會           54
學生28        3     國文,數學,自然     56,58,55
學生29        0
學生30        1           英文           55
學生31        1           數學           53
學生32        1           國文           52
學生33        1           數學           53
學生34        1           自然           59
學生35        1           社會           54
學生36        1           英文           50
學生37        0
學生38        2        國文,英文        55,54
學生39        0
學生40        2        國文,數學        53,50
學生41        1           自然           56
學生42        0
學生43        1           自然           59
學生44        0
學生45        2        數學,社會        52,52
學生46        1           自然           56
學生47        2        英文,社會        59,50
學生48        1           自然           50
學生49        2        自然,社會        51,50
學生50        1           社會           54

In [20]:
#df要和df2合併
df_merged = pd.concat([df, df2], axis=1)
df_merged

,國文,英文,數學,自然,社會,總分,平均,排名,不及格科目數量,不及格科目,分數
學生,,,,,,,,,,,
學生1,50,59,55,63,68,295,59.0,50.0,3,"國文,英文,數學","50,59,55"
學生2,98,73,50,66,89,376,75.2,26.0,1,數學,50
學生3,80,98,75,74,91,418,83.6,2.0,0,,
學生4,58,95,97,92,61,403,80.6,12.0,1,國文,58
學生5,90,63,76,58,75,362,72.4,28.0,1,自然,58
學生6,84,89,58,94,75,400,80.0,13.0,1,數學,58
學生7,86,77,75,60,84,382,76.4,23.0,0,,
學生8,66,94,58,64,51,333,66.6,44.0,2,"數學,社會","58,51"
學生9,59,55,59,68,86,327,65.4,45.0,3,"國文,英文,數學","59,55,59"
學生10,89,66,88,96,72,411,82.2,6.0,0,,
學生11,93,99,88,61,64,405,81.0,9.0,0,,
學生12,58,79,89,63,94,383,76.6,22.0,1,國文,58
學生13,50,76,64,96,65,351,70.2,35.0,1,國文,50
學生14,87,63,71,82,51,354,70.8,33.0,1,社會,51
學生15,57,54,57,99,59,326,65.2,48.0,4,"國文,英文,數學,社會","57,54,57,59"
學生16,52,94,70,65,61,342,68.4,42.0,1,國文,52
學生17,87,99,67,79,78,410,82.0,7.0,0,,
學生18,88,55,75,72,97,387,77.4,20.0,1,英文,55
學生19,98,52,84,88,59,381,76.2,24.0,2,"英文,社會","52,59"
學生20,81,52,76,73,52,334,66.8,43.0,2,"英文,社會","52,52"
學生21,88,90,81,69,66,394,78.8,15.0,0,,
學生22,81,55,100,56,89,381,76.2,24.0,2,"英文,自然","55,56"
學生23,91,50,69,88,89,387,77.4,20.0,1,英文,50
學生24,71,98,64,61,50,344,68.8,41.0,1,社會,50
學生25,91,77,75,86,85,414,82.8,4.0,0,,
學生26,64,59,57,88,85,353,70.6,34.0,2,"英文,數學","59,57"
學生27,93,80,83,90,54,400,80.0,13.0,1,社會,54
學生28,56,83,58,55,70,322,64.4,49.0,3,"國文,數學,自然","56,58,55"
學生29,84,91,94,100,97,466,93.2,1.0,0,,
學生30,76,55,73,93,97,394,78.8,15.0,1,英文,55
學生31,69,95,53,71,73,361,72.2,30.0,1,數學,53
學生32,52,69,76,92,76,365,73.0,27.0,1,國文,52
學生33,94,94,53,93,73,407,81.4,8.0,1,數學,53
學生34,88,73,93,59,91,404,80.8,11.0,1,自然,59
學生35,68,62,83,80,54,347,69.4,37.0,1,社會,54
學生36,94,50,68,70,75,357,71.4,31.0,1,英文,50
學生37,60,99,70,79,97,405,81.0,9.0,0,,
學生38,55,54,84,62,72,327,65.4,45.0,2,"國文,英文","55,54"
學生39,62,86,62,73,64,347,69.4,37.0,0,,
學生40,53,100,50,82,72,357,71.4,31.0,2,"國文,數學","53,50"
學生41,85,90,91,56,70,392,78.4,17.0,1,自然,56
學生42,68,100,66,82,96,412,82.4,5.0,0,,
學生43,61,86,65,59,76,347,69.4,37.0,1,自然,59
學生44,77,81,73,90,94,415,83.0,3.0,0,,
學生45,77,67,52,79,52,327,65.4,45.0,2,"數學,社會","52,52"
學生46,60,82,84,56,69,351,70.2,35.0,1,自然,56
學生47,85,59,71,97,50,362,72.4,28.0,2,"英文,社會","59,50"
學生48,82,83,99,50,77,391,78.2,18.0,1,自然,50
學生49,73,82,91,51,50,347,69.4,37.0,2,"自然,社會","51,50"
學生50,77,95,78,84,54,388,77.6,19.0,1,社會,54