In [1]:
import numpy as np
import pandas as pd

df = pd.DataFrame(np.arange(16).reshape(4, 4),
                  index=['台北', '台中', '高雄', '台南'],
                  columns=['one', 'two', 'three', 'four'])

df

    one  two  three  four
台北    0    1      2     3
台中    4    5      6     7
高雄    8    9     10    11
台南   12   13     14    15

In [2]:
# drop 刪除
df.drop(index=['台北', '高雄'], inplace=True)
df

    one  two  three  four
台中    4    5      6     7
台南   12   13     14    15

In [7]:
#排序和排名

scores = np.random.randint(50,101,size = (50,5))
df = pd.DataFrame(scores, 
                  columns=['國文', '英文', '數學', '自然', '社會'],
                  index=['學生' + str(i) for i in range(1, 51)])
df.index.name = '學生'
df.columns.name = '科目'
df

科目    國文   英文   數學   自然   社會
學生
學生1   57   78   54   52  100
學生2   71   76   76   56   93
學生3   87   63  100   81   97
學生4   97   61   59   75   55
學生5   71   97   93   65   94
學生6   50   68   81   77   68
學生7   93   90   67   67   69
學生8   69   73   52   94   87
學生9   52   63   91   53   98
學生10  55   69   98   64   64
學生11  86   60   78   72   60
學生12  99   99   64   70   74
學生13  88  100   97   91   80
學生14  68   69   84   52   70
學生15  76   61   59   69   55
學生16  68   58   55   61   69
學生17  86   79   79   71   76
學生18  51   59   99   79   50
學生19  60   50   92   66   92
學生20  83   90   83   67   92
學生21  92   58   54   88   82
學生22  97   89   87   83   89
學生23  73   91   98   89   54
學生24  64   79   68   59   62
學生25  74   95   51   64   99
學生26  57   90   85   91   86
學生27  65   68   72   92   90
學生28  93   81   90   70   65
學生29  56   65   73   73   75
學生30  66   67   59   57   89
學生31  76   57   72   90   52
學生32  52   63   75  100   77
學生33  61   52   65   99   86
學生34  54   62   91   52   55
學生35  76   88   89   91   53
學生36  80   66   91   78   91
學生37  96   68   93   98   64
學生38  67   90   82   51   76
學生39  90   85   79   65   58
學生40  73   57  100   62   73
學生41  62   77   90   56   53
學生42  50   50   67   87   85
學生43  87  100   83   94   70
學生44  77   59   95   58   95
學生45  96   93   99   58   66
學生46  88   67   76   55   53
學生47  79   78   59   77   68
學生48  79   73   50   68   86
學生49  96   81   77   50   80
學生50  76   96   97   73   72

In [12]:
#排序和排名

scores = np.random.randint(50,101,size = (50,5))
df = pd.DataFrame(scores, 
                  columns=['國文', '英文', '數學', '自然', '社會'],
                  index=['學生' + str(i) for i in range(1, 51)])
df.index.name = '學生'
df.columns.name = '科目'
sum_values = df.sum(axis=1)
mean_values = df.mean(axis=1)
df['總分'] = sum_values
df['平均'] = mean_values
df

科目     國文   英文  數學   自然  社會   總分    平均
學生
學生1    87   95  72   82  65  401  80.2
學生2    70   79  63   58  89  359  71.8
學生3    68   71  91   57  73  360  72.0
學生4    57   73  92   65  54  341  68.2
學生5    68   67  87   50  77  349  69.8
學生6    88   79  61   69  62  359  71.8
學生7    96   77  65   89  76  403  80.6
學生8    54   75  80   64  94  367  73.4
學生9    82   62  58   74  69  345  69.0
學生10   67   89  85   59  90  390  78.0
學生11   89   62  55   71  59  336  67.2
學生12   61   92  64   51  87  355  71.0
學生13   50   80  76   96  97  399  79.8
學生14   54   93  51   72  69  339  67.8
學生15  100   62  81   60  58  361  72.2
學生16   88  100  77   77  52  394  78.8
學生17   92   90  62   83  62  389  77.8
學生18   99   54  93   84  81  411  82.2
學生19   80   60  85   82  89  396  79.2
學生20   69   60  98   51  54  332  66.4
學生21   68   73  85   69  84  379  75.8
學生22   74   91  78   56  73  372  74.4
學生23   63   95  93   87  93  431  86.2
學生24   76   67  61   59  59  322  64.4
學生25   69   61  65   55  75  325  65.0
學生26   97   52  60   50  62  321  64.2
學生27   95   61  74   94  53  377  75.4
學生28   65   78  59   92  86  380  76.0
學生29   77   92  97   59  97  422  84.4
學生30   52   92  92   84  58  378  75.6
學生31   79   88  93   56  67  383  76.6
學生32   86   89  59   64  75  373  74.6
學生33   98   66  73   63  79  379  75.8
學生34   67   63  72   59  52  313  62.6
學生35   79   52  50   64  71  316  63.2
學生36   88   83  59   55  75  360  72.0
學生37   69   68  51   89  70  347  69.4
學生38   97   74  97   76  99  443  88.6
學生39   67   88  82   66  69  372  74.4
學生40   59   97  61   75  60  352  70.4
學生41   65   58  51   57  58  289  57.8
學生42   95   84  78   94  99  450  90.0
學生43   54   99  53   78  86  370  74.0
學生44   86   88  99   56  88  417  83.4
學生45   59   94  67  100  93  413  82.6
學生46   98   87  70   70  71  396  79.2
學生47   74   82  81   86  75  398  79.6
學生48   78   51  96   80  74  379  75.8
學生49   54   62  65   91  64  336  67.2
學生50   53   92  86   72  69  372  74.4

In [21]:
#排序和排名
#rank()
rank_values = sum_values.rank(method='min', ascending=False)
df['排名'] = rank_values
df

科目     國文   英文  數學   自然  社會   總分    平均    排名
學生
學生1    87   95  72   82  65  401  80.2   9.0
學生2    70   79  63   58  89  359  71.8  33.0
學生3    68   71  91   57  73  360  72.0  31.0
學生4    57   73  92   65  54  341  68.2  40.0
學生5    68   67  87   50  77  349  69.8  37.0
學生6    88   79  61   69  62  359  71.8  33.0
學生7    96   77  65   89  76  403  80.6   8.0
學生8    54   75  80   64  94  367  73.4  29.0
學生9    82   62  58   74  69  345  69.0  39.0
學生10   67   89  85   59  90  390  78.0  15.0
學生11   89   62  55   71  59  336  67.2  42.0
學生12   61   92  64   51  87  355  71.0  35.0
學生13   50   80  76   96  97  399  79.8  10.0
學生14   54   93  51   72  69  339  67.8  41.0
學生15  100   62  81   60  58  361  72.2  30.0
學生16   88  100  77   77  52  394  78.8  14.0
學生17   92   90  62   83  62  389  77.8  16.0
學生18   99   54  93   84  81  411  82.2   7.0
學生19   80   60  85   82  89  396  79.2  12.0
學生20   69   60  98   51  54  332  66.4  44.0
學生21   68   73  85   69  84  379  75.8  19.0
學生22   74   91  78   56  73  372  74.4  25.0
學生23   63   95  93   87  93  431  86.2   3.0
學生24   76   67  61   59  59  322  64.4  46.0
學生25   69   61  65   55  75  325  65.0  45.0
學生26   97   52  60   50  62  321  64.2  47.0
學生27   95   61  74   94  53  377  75.4  23.0
學生28   65   78  59   92  86  380  76.0  18.0
學生29   77   92  97   59  97  422  84.4   4.0
學生30   52   92  92   84  58  378  75.6  22.0
學生31   79   88  93   56  67  383  76.6  17.0
學生32   86   89  59   64  75  373  74.6  24.0
學生33   98   66  73   63  79  379  75.8  19.0
學生34   67   63  72   59  52  313  62.6  49.0
學生35   79   52  50   64  71  316  63.2  48.0
學生36   88   83  59   55  75  360  72.0  31.0
學生37   69   68  51   89  70  347  69.4  38.0
學生38   97   74  97   76  99  443  88.6   2.0
學生39   67   88  82   66  69  372  74.4  25.0
學生40   59   97  61   75  60  352  70.4  36.0
學生41   65   58  51   57  58  289  57.8  50.0
學生42   95   84  78   94  99  450  90.0   1.0
學生43   54   99  53   78  86  370  74.0  28.0
學生44   86   88  99   56  88  417  83.4   5.0
學生45   59   94  67  100  93  413  82.6   6.0
學生46   98   87  70   70  71  396  79.2  12.0
學生47   74   82  81   86  75  398  79.6  11.0
學生48   78   51  96   80  74  379  75.8  19.0
學生49   54   62  65   91  64  336  67.2  42.0
學生50   53   92  86   72  69  372  74.4  25.0

In [22]:
#sort_values()
#sort_index()
df1 = df.sort_values(by='總分', ascending=False)
df1

科目     國文   英文  數學   自然  社會   總分    平均    排名
學生
學生42   95   84  78   94  99  450  90.0   1.0
學生38   97   74  97   76  99  443  88.6   2.0
學生23   63   95  93   87  93  431  86.2   3.0
學生29   77   92  97   59  97  422  84.4   4.0
學生44   86   88  99   56  88  417  83.4   5.0
學生45   59   94  67  100  93  413  82.6   6.0
學生18   99   54  93   84  81  411  82.2   7.0
學生7    96   77  65   89  76  403  80.6   8.0
學生1    87   95  72   82  65  401  80.2   9.0
學生13   50   80  76   96  97  399  79.8  10.0
學生47   74   82  81   86  75  398  79.6  11.0
學生19   80   60  85   82  89  396  79.2  12.0
學生46   98   87  70   70  71  396  79.2  12.0
學生16   88  100  77   77  52  394  78.8  14.0
學生10   67   89  85   59  90  390  78.0  15.0
學生17   92   90  62   83  62  389  77.8  16.0
學生31   79   88  93   56  67  383  76.6  17.0
學生28   65   78  59   92  86  380  76.0  18.0
學生21   68   73  85   69  84  379  75.8  19.0
學生33   98   66  73   63  79  379  75.8  19.0
學生48   78   51  96   80  74  379  75.8  19.0
學生30   52   92  92   84  58  378  75.6  22.0
學生27   95   61  74   94  53  377  75.4  23.0
學生32   86   89  59   64  75  373  74.6  24.0
學生50   53   92  86   72  69  372  74.4  25.0
學生22   74   91  78   56  73  372  74.4  25.0
學生39   67   88  82   66  69  372  74.4  25.0
學生43   54   99  53   78  86  370  74.0  28.0
學生8    54   75  80   64  94  367  73.4  29.0
學生15  100   62  81   60  58  361  72.2  30.0
學生3    68   71  91   57  73  360  72.0  31.0
學生36   88   83  59   55  75  360  72.0  31.0
學生6    88   79  61   69  62  359  71.8  33.0
學生2    70   79  63   58  89  359  71.8  33.0
學生12   61   92  64   51  87  355  71.0  35.0
學生40   59   97  61   75  60  352  70.4  36.0
學生5    68   67  87   50  77  349  69.8  37.0
學生37   69   68  51   89  70  347  69.4  38.0
學生9    82   62  58   74  69  345  69.0  39.0
學生4    57   73  92   65  54  341  68.2  40.0
學生14   54   93  51   72  69  339  67.8  41.0
學生11   89   62  55   71  59  336  67.2  42.0
學生49   54   62  65   91  64  336  67.2  42.0
學生20   69   60  98   51  54  332  66.4  44.0
學生25   69   61  65   55  75  325  65.0  45.0
學生24   76   67  61   59  59  322  64.4  46.0
學生26   97   52  60   50  62  321  64.2  47.0
學生35   79   52  50   64  71  316  63.2  48.0
學生34   67   63  72   59  52  313  62.6  49.0
學生41   65   58  51   57  58  289  57.8  50.0