In [ ]:
#AI建立一個function
#資料來源:scores = np.random.randint(50,101,size=(50, 5))
#欄位: ['國文', '英文', '數學', '自然', '社會','總分','平均','排名']
#索引: ['學生' + str(i) for i in range(1, 51)]
#建立DataFrame
import numpy as np
import pandas as pd 

def build_scores_dataframe(scores):
    df = pd.DataFrame(scores,
                      columns=['國文', '英文', '數學', '自然', '社會'],
                      index=['學生' + str(i) for i in range(1, 51)])
    df.index.name = '學生'
    df.columns.name = '科目'
    sum_values = df.sum(axis=1)
    mean_values = df.mean(axis=1)
    df['總分'] = sum_values
    df['平均'] = mean_values
    rank_values = sum_values.rank(method='min', ascending=False)
    df['排名'] = rank_values
    return df

In [12]:
scores = np.random.randint(50,101,size=(50, 5))
df = build_scores_dataframe(scores)
df
#AI建立一個function
#依據df
#建立1個統計的DataFrame
#欄位: ['國文', '英文', '數學', '自然', '社會']
#欄位: ['平均', '最高', '最低', '中間值']

科目     國文   英文  數學   自然   社會   總分    平均    排名
學生
學生1    67   68  83   97   99  414  82.8   4.0
學生2    79   62  73   52   70  336  67.2  44.0
學生3    66   58  52   64   59  299  59.8  49.0
學生4    64   65  83   92   58  362  72.4  33.0
學生5    85   87  98   61   63  394  78.8  14.0
學生6    78   54  50   60   52  294  58.8  50.0
學生7    58   91  88   61   64  362  72.4  33.0
學生8   100   89  96   76   52  413  82.6   5.0
學生9    76   56  71   61   79  343  68.6  43.0
學生10   78   93  90   62   68  391  78.2  17.0
學生11   67   57  76   55  100  355  71.0  36.0
學生12   99   70  69   88   56  382  76.4  20.0
學生13   98   89  81   81   58  407  81.4   7.0
學生14   81   91  75   72   83  402  80.4  10.0
學生15   69   83  90   53   85  380  76.0  21.0
學生16   71   52  77   91   97  388  77.6  18.0
學生17   66   64  75   90   52  347  69.4  42.0
學生18   95   65  85   88   97  430  86.0   2.0
學生19   64   99  65   57   92  377  75.4  24.0
學生20   80  100  62  100   64  406  81.2   8.0
學生21   96   98  59   65   61  379  75.8  22.0
學生22   90   98  96   97   57  438  87.6   1.0
學生23   80   61  97   64   92  394  78.8  14.0
學生24   76   99  86   69   80  410  82.0   6.0
學生25   72   91  73   79   83  398  79.6  13.0
學生26   94   51  75  100   59  379  75.8  22.0
學生27   89   90  80   67   59  385  77.0  19.0
學生28   66   58  99   97   50  370  74.0  30.0
學生29   70   86  61   78   57  352  70.4  38.0
學生30   97   58  59   58   83  355  71.0  36.0
學生31   63   96  81   78   86  404  80.8   9.0
學生32   98   85  97   62   82  424  84.8   3.0
學生33   76   65  57   77   89  364  72.8  32.0
學生34   62   75  53   81   80  351  70.2  41.0
學生35   78   76  64   62   53  333  66.6  47.0
學生36   78   77  57   91   89  392  78.4  16.0
學生37   52   73  94   69   69  357  71.4  35.0
學生38   83   53  89   63   88  376  75.2  26.0
學生39   77   83  73   92   77  402  80.4  10.0
學生40   77   84  50   87   75  373  74.6  27.0
學生41   93   58  99   67   56  373  74.6  27.0
學生42   62   54  62   63   95  336  67.2  44.0
學生43   64  100  71   89   53  377  75.4  24.0
學生44   90   62  92   94   61  399  79.8  12.0
學生45   85   64  86   58   80  373  74.6  27.0
學生46   93   81  64   60   54  352  70.4  38.0
學生47   78   67  52   93   80  370  74.0  30.0
學生48   62   59  83   55   53  312  62.4  48.0
學生49   53   65  68   74   74  334  66.8  46.0
學生50   60   91  70   66   65  352  70.4  38.0

In [13]:
#建立1個統計的DataFrame
def create_statistics_dataframe(df):
    cols = ['國文', '英文', '數學', '自然', '社會']
    stats = df[cols].agg(['mean', 'max', 'min', 'median'])
    stats.index = ['平均', '最高', '最低', '中間值']
    return stats
create_statistics_dataframe(df)

科目      國文      英文     數學      自然      社會
平均    77.1   75.02  75.72   74.32   71.76
最高   100.0  100.00  99.00  100.00  100.00
最低    52.0   51.00  50.00   52.00   50.00
中間值   77.5   74.00  75.00   70.50   69.50